# Generated by Django 3.1.12 on 2025-11-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20251130_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
