# Generated by Django 3.1.12 on 2025-11-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('COMMENT', 'New Comment'), ('STATUS', 'Status Update'), ('ESCALATION', 'Issue Escalated'), ('NEW_ISSUE', 'New Issue Reported')], default='COMMENT', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
