# Generated by Django 3.1.12 on 2025-12-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_auto_20251130_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='last_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
