# Generated by Django 3.1.12 on 2025-12-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='representative_level',
            field=models.CharField(blank=True, choices=[('VILLAGE', 'Village'), ('TALUKA', 'Taluka'), ('DISTRICT', 'District'), ('STATE', 'State')], default='TALUKA', max_length=20, null=True),
        ),
    ]
